// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCAOeAyihApZeQ2l2VX8FnFl4OK7saxLzs',
    appId: '1:973547304455:web:82e833c4330c9af08fdca2',
    messagingSenderId: '973547304455',
    projectId: 'client-management-system-4efb2',
    authDomain: 'client-management-system-4efb2.firebaseapp.com',
    storageBucket: 'client-management-system-4efb2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCc6T2xNY66Ps_voN02vtYQ6g8E23fgiLc',
    appId: '1:973547304455:android:04d5a8cdff82ec7a8fdca2',
    messagingSenderId: '973547304455',
    projectId: 'client-management-system-4efb2',
    storageBucket: 'client-management-system-4efb2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfAIElci5YVmap1djgzhvCQJV_R9XeZDU',
    appId: '1:973547304455:ios:d0911019920027ba8fdca2',
    messagingSenderId: '973547304455',
    projectId: 'client-management-system-4efb2',
    storageBucket: 'client-management-system-4efb2.appspot.com',
    iosBundleId: 'com.example.clientManagementSystem',
  );
}
